// Supabase Edge Function: Conversational Chatbot & Voice Booking
// Deno runtime, TypeScript
// Receives chat/voice message, calls Groq API, returns response

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY") ?? "";
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405 });
  }

  const { message, user_id } = await req.json();
  if (!message) {
    return new Response(JSON.stringify({ error: "Missing message" }), { status: 400 });
  }

  // Prepare prompt for Groq API
  const prompt = `User (${user_id ?? "unknown"}) says: ${message}\nRespond as a helpful LuxeRide assistant. If the message is a booking request, ask for details or confirm the booking.`;

  let groqResponse: Record<string, unknown> | null = null;
  try {
    const groqFetch = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mixtral-8x7b-32768",
        messages: [
          { role: "system", content: "You are a conversational assistant for a luxury ride service." },
          { role: "user", content: prompt },
        ],
        max_tokens: 256,
        temperature: 0.5,
      }),
    });
    groqResponse = await groqFetch.json();
  } catch (e) {
    return new Response(JSON.stringify({ error: "Groq API call failed", details: e.message }), { status: 500 });
  }

  const aiResult = groqResponse?.choices?.[0]?.message?.content ?? "";

  return new Response(JSON.stringify({
    response: aiResult,
    message: "Response generated by AI. Integrate with booking system in production."
  }), {
    headers: { "Content-Type": "application/json" },
    status: 200,
  });
}); 