// Supabase Edge Function: Customer Experience Analytics
// Deno runtime, TypeScript
// Receives feedback, chat logs, or booking data, calls Groq API, returns insights and recommendations

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY") ?? "";
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405 });
  }

  const { feedback, chat_logs, booking_data } = await req.json();

  // Placeholder: Simulate feedback/chat logs/booking data if not provided
  const feedbackVal = feedback ?? [ { rating: 5, comments: "Great ride!" }, { rating: 3, comments: "Average experience." } ];
  const chatLogsVal = chat_logs ?? [ { user: "u1", message: "How do I book a chopper?" }, { user: "u2", message: "Thanks for the ride!" } ];
  const bookingVal = booking_data ?? [ { id: "b1", status: "completed" }, { id: "b2", status: "cancelled" } ];

  // Prepare prompt for Groq API
  const prompt = `Given the following feedback: ${JSON.stringify(feedbackVal)},\n` +
    `chat logs: ${JSON.stringify(chatLogsVal)},\n` +
    `and booking data: ${JSON.stringify(bookingVal)},\n` +
    `analyze for customer experience insights and suggest improvements or follow-up campaigns. Return a summary and recommendations.`;

  let groqResponse: Record<string, unknown> | null = null;
  try {
    const groqFetch = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mixtral-8x7b-32768",
        messages: [
          { role: "system", content: "You are a customer experience analytics assistant for a luxury ride service." },
          { role: "user", content: prompt },
        ],
        max_tokens: 512,
        temperature: 0.3,
      }),
    });
    groqResponse = await groqFetch.json();
  } catch (e) {
    return new Response(JSON.stringify({ error: "Groq API call failed", details: e.message }), { status: 500 });
  }

  const aiResult = groqResponse?.choices?.[0]?.message?.content ?? "";

  return new Response(JSON.stringify({
    cx_insights: aiResult,
    feedback: feedbackVal,
    chat_logs: chatLogsVal,
    booking_data: bookingVal,
    message: "Insights generated by AI. Replace with real data in production."
  }), {
    headers: { "Content-Type": "application/json" },
    status: 200,
  });
}); 