// Supabase Edge Function: Demand Forecasting & Fleet Allocation
// Deno runtime, TypeScript
// Receives area/time window, queries bookings/events, calls Groq API, returns demand/fleet recommendations

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY") ?? "";
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405 });
  }

  const { area, time_window } = await req.json();

  // 1. Query recent bookings and events from Supabase
  // Placeholder: Simulate recent bookings and events
  const recentBookings = [
    { id: "b1", pickup: { lat: -1.2921, lng: 36.8219 }, time: "2024-06-01T10:00:00Z" },
    { id: "b2", pickup: { lat: -1.3500, lng: 36.7500 }, time: "2024-06-01T10:15:00Z" },
    { id: "b3", pickup: { lat: -0.7167, lng: 36.4333 }, time: "2024-06-01T10:30:00Z" },
  ];
  const upcomingEvents = [
    { name: "Naivasha Rally", location: { lat: -0.7167, lng: 36.4333 }, time: "2024-06-01T12:00:00Z" },
    { name: "Nairobi Rush Hour", location: { lat: -1.2921, lng: 36.8219 }, time: "2024-06-01T17:00:00Z" },
  ];

  // 2. Prepare prompt for Groq API
  const prompt = `Given the following recent bookings: ${JSON.stringify(recentBookings)},\n` +
    `and upcoming events: ${JSON.stringify(upcomingEvents)},\n` +
    `for the area: ${JSON.stringify(area)} and time window: ${JSON.stringify(time_window)},\n` +
    `predict demand spikes and suggest how to allocate the fleet (cars, choppers, boats) proactively. Return a summary and specific recommendations.`;

  // 3. Call Groq API (LLM) to predict demand and recommend allocation
  let groqResponse: Record<string, unknown> | null = null;
  try {
    const groqFetch = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mixtral-8x7b-32768",
        messages: [
          { role: "system", content: "You are a demand forecasting and fleet allocation assistant for a luxury ride service." },
          { role: "user", content: prompt },
        ],
        max_tokens: 512,
        temperature: 0.3,
      }),
    });
    groqResponse = await groqFetch.json();
  } catch (e) {
    return new Response(JSON.stringify({ error: "Groq API call failed", details: e.message }), { status: 500 });
  }

  // 4. Parse Groq response
  const aiResult = groqResponse?.choices?.[0]?.message?.content ?? "";

  // 5. Return demand forecast and fleet allocation recommendations
  return new Response(JSON.stringify({
    demand_forecast: aiResult,
    recent_bookings: recentBookings,
    upcoming_events: upcomingEvents,
    message: "Forecast generated by AI. Replace data queries with real DB calls in production."
  }), {
    headers: { "Content-Type": "application/json" },
    status: 200,
  });
}); 