// Supabase Edge Function: Fraud Detection & Safety Monitoring
// Deno runtime, TypeScript
// Receives booking/ride data, calls Groq API, returns alerts or recommendations

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY") ?? "";
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405 });
  }

  const { booking_data, ride_data } = await req.json();

  // Placeholder: Simulate booking/ride data if not provided
  const booking = booking_data ?? { id: "b1", user_id: "u1", vehicle_id: "v1", status: "completed", price: 100 };
  const ride = ride_data ?? { route: [ { lat: -1.2921, lng: 36.8219 }, { lat: -1.3500, lng: 36.7500 } ], duration: 30 };

  // Prepare prompt for Groq API
  const prompt = `Given the following booking: ${JSON.stringify(booking)},\n` +
    `and ride data: ${JSON.stringify(ride)},\n` +
    `analyze for suspicious or unsafe patterns (e.g., multiple bookings, route deviations, safety issues). Return any alerts or recommendations.`;

  let groqResponse: Record<string, unknown> | null = null;
  try {
    const groqFetch = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mixtral-8x7b-32768",
        messages: [
          { role: "system", content: "You are a fraud detection and safety monitoring assistant for a luxury ride service." },
          { role: "user", content: prompt },
        ],
        max_tokens: 256,
        temperature: 0.2,
      }),
    });
    groqResponse = await groqFetch.json();
  } catch (e) {
    return new Response(JSON.stringify({ error: "Groq API call failed", details: e.message }), { status: 500 });
  }

  const aiResult = groqResponse?.choices?.[0]?.message?.content ?? "";

  return new Response(JSON.stringify({
    fraud_alerts: aiResult,
    booking: booking,
    ride: ride,
    message: "Alerts generated by AI. Replace with real data in production."
  }), {
    headers: { "Content-Type": "application/json" },
    status: 200,
  });
}); 