// Supabase Edge Function: Predictive Maintenance
// Deno runtime, TypeScript
// Receives telemetry data or vehicle ID, calls Groq API, returns maintenance recommendations

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY") ?? "";
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405 });
  }

  const { vehicle_id, telemetry } = await req.json();

  // Placeholder: Simulate telemetry if not provided
  const telemetryData = telemetry ?? {
    speed: 60,
    fuel_level: 50,
    engine_temp: 90,
    maintenance_flag: false
  };

  // Prepare prompt for Groq API
  const prompt = `Given the following telemetry for vehicle ${vehicle_id ?? "unknown"}: ${JSON.stringify(telemetryData)},\n` +
    `analyze if maintenance is needed soon and explain your reasoning. Return a recommendation and reason.`;

  let groqResponse: Record<string, unknown> | null = null;
  try {
    const groqFetch = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mixtral-8x7b-32768",
        messages: [
          { role: "system", content: "You are a predictive maintenance assistant for a luxury ride service." },
          { role: "user", content: prompt },
        ],
        max_tokens: 256,
        temperature: 0.2,
      }),
    });
    groqResponse = await groqFetch.json();
  } catch (e) {
    return new Response(JSON.stringify({ error: "Groq API call failed", details: e.message }), { status: 500 });
  }

  const aiResult = groqResponse?.choices?.[0]?.message?.content ?? "";

  return new Response(JSON.stringify({
    maintenance_recommendation: aiResult,
    telemetry: telemetryData,
    message: "Recommendation generated by AI. Replace with real telemetry in production."
  }), {
    headers: { "Content-Type": "application/json" },
    status: 200,
  });
}); 