// Supabase Edge Function: Personalization & Recommendation Engine
// Deno runtime, TypeScript
// Receives user ID and context, calls Groq API, returns personalized recommendations

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY") ?? "";
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405 });
  }

  const { user_id, context } = await req.json();

  // Placeholder: Simulate user context if not provided
  const userContext = context ?? {
    loyalty_tier: "Gold",
    last_ride: "helicopter",
    preferences: ["scenic tours", "speedboat"]
  };

  // Prepare prompt for Groq API
  const prompt = `For user ${user_id ?? "unknown"} with context: ${JSON.stringify(userContext)},\n` +
    `suggest personalized ride or offer recommendations. Return a list and a brief explanation.`;

  let groqResponse: Record<string, unknown> | null = null;
  try {
    const groqFetch = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mixtral-8x7b-32768",
        messages: [
          { role: "system", content: "You are a personalization and recommendation assistant for a luxury ride service." },
          { role: "user", content: prompt },
        ],
        max_tokens: 256,
        temperature: 0.3,
      }),
    });
    groqResponse = await groqFetch.json();
  } catch (e) {
    return new Response(JSON.stringify({ error: "Groq API call failed", details: e.message }), { status: 500 });
  }

  const aiResult = groqResponse?.choices?.[0]?.message?.content ?? "";

  return new Response(JSON.stringify({
    recommendations: aiResult,
    user_context: userContext,
    message: "Recommendations generated by AI. Replace with real user data in production."
  }), {
    headers: { "Content-Type": "application/json" },
    status: 200,
  });
}); 