// Supabase Edge Function: Smart Dispatch & Route Optimization
// Deno runtime, TypeScript
// Receives booking request, queries vehicles, calls Groq API, returns assignment

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

// Placeholder: Replace with your actual Groq API key
const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY") ?? "";
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405 });
  }

  const { pickup_location, dropoff_location, user_id } = await req.json();
  if (!pickup_location || !dropoff_location || !user_id) {
    return new Response(JSON.stringify({ error: "Missing required fields" }), { status: 400 });
  }

  // 1. Query available vehicles from Supabase
  // (In production, use the Supabase client with service role key)
  // Placeholder: Simulate available vehicles
  const availableVehicles = [
    { id: "veh1", type: "car", location: { lat: -1.2921, lng: 36.8219 }, status: "available" },
    { id: "veh2", type: "chopper", location: { lat: -1.3500, lng: 36.7500 }, status: "available" },
    { id: "veh3", type: "boat", location: { lat: -0.7167, lng: 36.4333 }, status: "available" },
  ];

  // 2. Prepare prompt for Groq API
  const prompt = `Given the following available vehicles: ${JSON.stringify(availableVehicles)},\n` +
    `and a booking request from user ${user_id} with pickup at ${JSON.stringify(pickup_location)} and dropoff at ${JSON.stringify(dropoff_location)},\n` +
    `which vehicle should be assigned for optimal ETA and efficiency? Return the vehicle id and a brief reason.`;

  // 3. Call Groq API (LLM) to select optimal vehicle
  let groqResponse: any = null;
  try {
    const groqFetch = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mixtral-8x7b-32768",
        messages: [
          { role: "system", content: "You are a smart dispatch assistant for a luxury ride service." },
          { role: "user", content: prompt },
        ],
        max_tokens: 256,
        temperature: 0.2,
      }),
    });
    groqResponse = await groqFetch.json();
  } catch (e) {
    return new Response(JSON.stringify({ error: "Groq API call failed", details: e.message }), { status: 500 });
  }

  // 4. Parse Groq response
  const aiResult = groqResponse?.choices?.[0]?.message?.content ?? "";

  // 5. Return assignment and route details
  return new Response(JSON.stringify({
    assigned_vehicle: aiResult,
    available_vehicles: availableVehicles,
    message: "Assignment generated by AI. Replace vehicle query with real DB call in production."
  }), {
    headers: { "Content-Type": "application/json" },
    status: 200,
  });
});
