// Supabase Edge Function: In-Vehicle Smart Ads
// Deno runtime, TypeScript
// Receives trip/user context, calls Groq API, returns targeted ad recommendations

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY") ?? "";
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405 });
  }

  const { trip_context, user_context } = await req.json();

  // Placeholder: Simulate trip/user context if not provided
  const trip = trip_context ?? { route: [ { lat: -1.2921, lng: 36.8219 }, { lat: -1.3500, lng: 36.7500 } ], vehicle_type: "car" };
  const user = user_context ?? { loyalty_tier: "Gold", preferences: ["concierge", "hotel"] };

  // Prepare prompt for Groq API
  const prompt = `Given the following trip context: ${JSON.stringify(trip)},\n` +
    `and user context: ${JSON.stringify(user)},\n` +
    `generate a list of targeted in-vehicle ad recommendations. Return the ads and a brief explanation.`;

  let groqResponse: Record<string, unknown> | null = null;
  try {
    const groqFetch = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mixtral-8x7b-32768",
        messages: [
          { role: "system", content: "You are an in-vehicle ad targeting assistant for a luxury ride service." },
          { role: "user", content: prompt },
        ],
        max_tokens: 256,
        temperature: 0.3,
      }),
    });
    groqResponse = await groqFetch.json();
  } catch (e) {
    return new Response(JSON.stringify({ error: "Groq API call failed", details: e.message }), { status: 500 });
  }

  const aiResult = groqResponse?.choices?.[0]?.message?.content ?? "";

  return new Response(JSON.stringify({
    ad_recommendations: aiResult,
    trip_context: trip,
    user_context: user,
    message: "Ads generated by AI. Replace with real data in production."
  }), {
    headers: { "Content-Type": "application/json" },
    status: 200,
  });
}); 