// Supabase Edge Function: Dynamic Pricing & Yield Management
// Deno runtime, TypeScript
// Receives ride details, supply/demand, event context; calls Groq API; returns price and reasoning

import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const GROQ_API_KEY = Deno.env.get("GROQ_API_KEY") ?? "";
const GROQ_API_URL = "https://api.groq.com/openai/v1/chat/completions";

serve(async (req: Request) => {
  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "Method not allowed" }), { status: 405 });
  }

  const { ride_details, supply, demand, event_context } = await req.json();

  // Placeholder: Simulate supply/demand/event context if not provided
  const supplyVal = supply ?? 10;
  const demandVal = demand ?? 20;
  const eventVal = event_context ?? "None";

  // Prepare prompt for Groq API
  const prompt = `Given the ride details: ${JSON.stringify(ride_details)},\n` +
    `current supply: ${supplyVal}, demand: ${demandVal}, event context: ${eventVal},\n` +
    `recommend a dynamic price for this ride and explain the reasoning. Return the price and a brief explanation.`;

  let groqResponse: Record<string, unknown> | null = null;
  try {
    const groqFetch = await fetch(GROQ_API_URL, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${GROQ_API_KEY}`,
      },
      body: JSON.stringify({
        model: "mixtral-8x7b-32768",
        messages: [
          { role: "system", content: "You are a dynamic pricing assistant for a luxury ride service." },
          { role: "user", content: prompt },
        ],
        max_tokens: 256,
        temperature: 0.2,
      }),
    });
    groqResponse = await groqFetch.json();
  } catch (e) {
    return new Response(JSON.stringify({ error: "Groq API call failed", details: e.message }), { status: 500 });
  }

  const aiResult = groqResponse?.choices?.[0]?.message?.content ?? "";

  return new Response(JSON.stringify({
    dynamic_price: aiResult,
    supply: supplyVal,
    demand: demandVal,
    event_context: eventVal,
    message: "Price generated by AI. Replace with real-time data in production."
  }), {
    headers: { "Content-Type": "application/json" },
    status: 200,
  });
}); 